Explicit initialization config could be quite interesting for
https://github.com/Yolean/kubernetes-kafka/pull/310
because when I investigated the timeouts there I found reports
that similar errors had been fixed by cleaning up (or trashing) persisted state.

> Detected a direct/mapped ByteBuffer in the image heap.
> A direct ByteBuffer has a pointer to unmanaged C memory,
> and C memory from the image generator is not available at image run time.
> A mapped ByteBuffer references a file descriptor,
> which is no longer open and mapped at run time.

Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Detected a direct/mapped ByteBuffer in the image heap. A direct ByteBuffer has a pointer to unmanaged C memory, and C memory from the image generator is not available at image run time.A mapped ByteBuffer references a file descriptor, which is no longer open and mapped at run time.   To see how this object got instantiated use -H:+TraceClassInitialization. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image run time by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Detailed message:
Trace:
	at parsing org.apache.zookeeper.server.persistence.FilePadding.padFile(FilePadding.java:78)
Call path from entry point to org.apache.zookeeper.server.persistence.FilePadding.padFile(FileChannel):
	at org.apache.zookeeper.server.persistence.FilePadding.padFile(FilePadding.java:76)